# Generated by Django 5.0.6 on 2024-05-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_vehicle_product_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
